### ISSUE TITLE
Playground GUI

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Leonidas-FTW#160]

**Comment by AnnaBel7** [comment]
I'm having a problem building the psi tree from the input code. From what I've seen, in order to create a dummy file (to apply the spartanization on) I need to have a PsiProject, but i can't figure  out how to create a dummy project without extending PsiTestCase. As it isn't a test file I don't want it to extend PsiTestCase.

Does anyone know about a better way to do that?

@TechnionYP5777/intellij-spartanizer

**Comment by AnnaBel7** [comment]
After a lot of problems with JavaFX I tried to implement the GUI using Swing and so far it seems to be working better, so for now this GUI will be using Swing instead of JavaFX.

**Comment by AnnaBel7** [comment]
The Leonidas tippers don't work in the playground yet, because of the Leonidas engine isn't finished yet. When the engine is ready, I will check it and fix if needed.

The nano patterns work when "createEnvironment" isn't called, this will be fixed soon.

**Comment by AnnaBel7** [comment]
It seems to be working with both Leonidas tippers and Nano Patterns.
