### ISSUE TITLE
Create "statements" stub method

### ISSUE THREAD

**Issue by michalcohen** [TechnionYP5777/Leonidas-FTW#99]
This one is a very tricky one and might take a longer time than other issues.
We want a stub method that represent any amount of statements that might be placed in **any** legal place in the code. For expamle:
while (true){
    statements(1);
    if (booleanEpression(2)){
        breake;
    }
    statements(3);
}

These are very not trivial decisions: 
 - which generic element to create in order to represent this behaviour?
 - where to place it and how to match it?
 - how to match it correctly?

Please start with consulting @AnnaBel7  about the current behaviour of "statement()" in the tip "IfDoubleNot". Later on, maybe @amirsagiv83 and @RoeyMaor have notes regarding anyBlock() that are related to this issue.

Good luck and keep updating!

**Comment by amirsagiv83** [comment]
@RoeiRaz 
Please Update on the progress. If this issue will take longer than a few days as we thought it might take, maybe it's better to postpone it to the next sprint.

**Comment by RoeyMaor** [comment]
@amirsagiv83 +1
This indeed seems challenging

**Comment by RoeiRaz** [comment]
Adding this feature requires a rework of some core components in the current version of leonidas (like the matching - a statements stub can match several sibling in the psi tree rather than a single sub tree). I've made several changes that would allow us to implement stubs like statements, but it isn't complete yet and i think it's better to put it on hold before the presentation.

**Comment by michalcohen** [comment]
Not relevant
